dist: trusty
sudo: required
language: php

addons:
  chrome: stable

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - php artisan dusk:chrome-driver

script:
  - vendor/bin/phpunit

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
