dist: trusty
sudo: required
language: php

addons:
  chrome: stable

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &


script:
  - vendor/bin/phpunit
