name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer update --no-progress --optimize-autoloader
      - name: Test
        run: docker-compose run --rm phpunit
      - name: codeclimate
        if: success() && (github.event_name != 'pull_request')
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          prefix: /app
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
